# Generated by Django 6.0.7 on 2026-07-29 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=150, unique=True)),
                ('name_en', models.CharField(max_length=150, unique=True)),
                ('short_name_ar', models.CharField(blank=True, max_length=50)),
                ('short_name_en', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('city_ar', models.CharField(blank=True, max_length=100)),
                ('city_en', models.CharField(blank=True, max_length=100)),
                ('google_maps_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name_ar'],
                'unique_together': {('name_ar', 'name_en')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_number', models.PositiveIntegerField(blank=True, null=True)),
                ('title_ar', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('sale_launch_date', models.DateField(blank=True, null=True)),
                ('sale_launch_time', models.TimeField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('gates_open_time', models.TimeField(blank=True, null=True)),
                ('match_start_time', models.TimeField(blank=True, null=True)),
                ('match_end_time', models.TimeField(blank=True, null=True)),
                ('kvs_required', models.BooleanField(default=True)),
                ('cms_status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('ready_for_cms', 'Ready for CMS'), ('sent_to_cms', 'Sent to CMS'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('away_club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='matches.club')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='matches.club')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='matches.venue')),
            ],
            options={
                'ordering': ['event_date', 'match_start_time', 'id'],
                'constraints': [models.UniqueConstraint(fields=('home_club', 'away_club', 'event_date'), name='unique_match_per_day')],
            },
        ),
    ]
