# Generated by Django 6.0.7 on 2026-07-29 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='unique_match_per_day',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='short_name_ar',
            new_name='short_name',
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='club',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='club',
            name='short_name_en',
        ),
        migrations.RemoveField(
            model_name='club',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='match',
            name='sale_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='sent_to_cms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='sent_to_cms_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_sent_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='match',
            name='cms_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('ready_for_cms', 'Ready for CMS'), ('sent_to_cms', 'Sent to CMS'), ('published', 'Published')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='match',
            name='kvs_required',
        ),
        migrations.RemoveField(
            model_name='match',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='match',
            name='sale_launch_date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='sale_launch_time',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='city_ar',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='updated_at',
        ),
    ]
