# Generated by Django 6.0.7 on 2026-07-31 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_remove_match_unique_match_per_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='الموظف المسؤول عن مباريات هذا النادي.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
