# Generated by Django 6.0.7 on 2026-08-02 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_assign_club_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=150, unique=True)),
                ('name_en', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='matches.competition'),
        ),
        migrations.CreateModel(
            name='UserCompetitionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='matches.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Competition Access',
                'verbose_name_plural': 'User Competition Access Grants',
                'ordering': ('competition__sort_order', 'user__username'),
                'unique_together': {('user', 'competition')},
            },
        ),
    ]
