# Generated by Django 6.0.7 on 2026-08-02 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_backfill_roshan_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='matches.competition'),
        ),
    ]
