# Generated by Django 6.0.7 on 2026-08-04 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_match_competition_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='match',
            name='discount_ticket_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
