# Generated by Django 6.0.7 on 2026-08-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_match_discount_code_match_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='actual_release_at',
            field=models.DateTimeField(blank=True, help_text='When tickets actually went live, if different from the planned sale_starts_at.', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='spl_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='spl_tickets_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='ticketing_plan_approved',
            field=models.BooleanField(default=False),
        ),
    ]
