# Generated by Django 6.0.7 on 2026-08-28 12:55

import matches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_club_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='plan_approval_file',
            field=models.FileField(blank=True, help_text='Signed ticketing plan approval document (image, PDF, or Office file).', null=True, upload_to='spl_plan_approvals/', validators=[matches.models.validate_plan_approval_file]),
        ),
    ]
