# Generated by Django 6.0.7 on 2026-08-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_match_plan_approval_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='has_images',
            field=models.BooleanField(default=False, help_text='Manually confirmed marketing images are ready. NOT the same as the KV/Webook Images readiness on the SPL Report, which is derived from checklist items - this field is only ever set by hand or left False by the calendar import.'),
        ),
        migrations.AddField(
            model_name='match',
            name='terms_ar',
            field=models.TextField(blank=True, default='لا يوجد استرجاع للمبالغ.'),
        ),
        migrations.AddField(
            model_name='match',
            name='terms_en',
            field=models.TextField(blank=True, default='Refund is not allowed.'),
        ),
    ]
