# Generated by Django 6.0.7 on 2026-08-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_match_has_images_match_terms_ar_match_terms_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='webook_purchase_url',
            field=models.URLField(blank=True, help_text='Public ticket purchase link on webook.com, filled in once the match goes live/published.'),
        ),
    ]
