# Generated by Django 6.0.7 on 2026-09-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_match_webook_purchase_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='plan_approval_file_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When the current plan_approval_file was uploaded.', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='spl_tickets_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the SPL team confirmed complimentary tickets were sent.', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='ticketing_plan_approved_at',
            field=models.DateTimeField(blank=True, help_text='When the SPL team confirmed the ticketing plan - kept even after the match is finished, for the Finished Matches history.', null=True),
        ),
    ]
