# Generated by Django 6.0.7 on 2026-09-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_match_plan_approval_file_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='release_delay_notes',
            field=models.TextField(blank=True, help_text='Details for the delay reason - e.g. which club/party the ticket design delay is on.'),
        ),
        migrations.AddField(
            model_name='match',
            name='release_delay_reason',
            field=models.CharField(blank=True, choices=[('spl_schedule_missing', "SPL hasn't provided the match schedule/dates yet"), ('ticket_design_delay', 'Ticket design delay'), ('other', 'Other')], max_length=30),
        ),
    ]
