# Generated by Django 6.0.7 on 2026-09-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_match_release_delay_notes_match_release_delay_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='release_delay_reason',
            field=models.CharField(blank=True, choices=[('spl_schedule_missing', "SPL hasn't provided the match schedule/dates yet"), ('kvs_delay', 'KVs delay'), ('other', 'Other')], max_length=30),
        ),
    ]
