# Generated by Django 6.0.7 on 2026-09-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_alter_match_release_delay_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_test_club',
            field=models.BooleanField(default=False, help_text='Excluded from every user-facing club list/filter/report - for dummy fixtures used in testing, not real teams.'),
        ),
    ]
