# Generated by Django 6.0.7 on 2026-09-14 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_club_is_test_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='seat_type',
            field=models.CharField(choices=[('seated', 'Seated (numbered)'), ('free', 'Free seated (unnumbered)')], default='seated', max_length=10),
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venue_images/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='matches.venue')),
            ],
            options={
                'ordering': ['venue__name_ar', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='VenueSeatingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. "CAT 1", "CAT 1 N", "Bronze - S".', max_length=30)),
                ('seat_count', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_seating_categories', to='matches.club')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_categories', to='matches.venue')),
            ],
            options={
                'verbose_name': 'Venue Seating Category',
                'verbose_name_plural': 'Venue Seating Categories',
                'ordering': ['venue__name_ar', 'club__name_ar', 'sort_order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'club', 'code'), name='unique_venue_club_seating_category_code')],
            },
        ),
    ]
