# Generated by Django 6.0.7 on 2026-09-14 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_venue_seat_type_venueimage_venueseatingcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_account',
            field=models.OneToOneField(blank=True, help_text='حساب النادي المباشر (Club Viewer) - مستقل عن المنسق.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_club', to=settings.AUTH_USER_MODEL),
        ),
    ]
