# Generated by Django 6.0.7 on 2026-09-14 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_club_club_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_account',
            field=models.OneToOneField(blank=True, help_text="The club's own direct account (Club Viewer) - independent of the coordinator.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_club', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(blank=True, help_text="The staff member responsible for this club's matches.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
