# Generated by Django 6.0.7 on 2026-09-14 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0020_alter_club_club_account_alter_club_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueseatingcategory',
            name='position_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_positions', to='matches.venueimage'),
        ),
        migrations.AddField(
            model_name='venueseatingcategory',
            name='position_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venueseatingcategory',
            name='position_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
