# Generated by Django 6.0.7 on 2026-09-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0021_venueseatingcategory_position_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='logo',
            field=models.ImageField(blank=True, help_text="Shown next to the competition's name (Club Dashboard, match detail, SPL reports) - optional, falls back to name-only when unset.", null=True, upload_to='competition_logos/'),
        ),
    ]
