# Generated by Django 6.0.7 on 2026-09-15 16:51, hand-edited to preserve
# existing position data: VenueSeatingCategory.position_image/position_x/
# position_y are being split out into their own MapPlacement model (a
# category can now be drawn on the map more than once - see
# matches/models.py's docstrings for why). The original auto-generated
# operation order (RemoveField before CreateModel) would have discarded
# every already-placed category's position with no way to recover it -
# reordered so CreateModel(MapPlacement) runs FIRST, a data migration
# copies every existing position into a MapPlacement row, and only THEN
# are the old fields removed.

import django.db.models.deletion
from django.db import migrations, models


def copy_positions_to_map_placements(apps, schema_editor):
    VenueSeatingCategory = apps.get_model("matches", "VenueSeatingCategory")
    MapPlacement = apps.get_model("matches", "MapPlacement")

    positioned = VenueSeatingCategory.objects.filter(
        position_image__isnull=False, position_x__isnull=False, position_y__isnull=False,
    )
    for category in positioned:
        MapPlacement.objects.create(
            venue_id=category.venue_id,
            club_id=category.club_id,
            position_image_id=category.position_image_id,
            category_id=category.id,
            zone_type="shared",
            position_x=category.position_x,
            position_y=category.position_y,
            sort_order=category.sort_order,
            is_active=True,
        )


def noop_reverse(apps, schema_editor):
    """Deliberately a no-op: reversing this migration only needs to make
    the old columns exist again (handled by Django re-adding them via the
    reverse of the later RemoveField operations) - it must NOT delete the
    MapPlacement rows, since those may have gained real data (new
    placements, gates, zone types) after this migration ran forward that
    the old columns could never represent anyway."""


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0022_competition_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueseatingcategory',
            name='color',
            field=models.CharField(blank=True, help_text="Hex color (e.g. #16a34a) for this category's map badge/legend swatch - shown alongside its code, never color-only.", max_length=20),
        ),
        migrations.CreateModel(
            name='VenueGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Gate 3", "North Gate".', max_length=100)),
                ('color', models.CharField(blank=True, help_text="Hex color (e.g. #2563eb) for this gate's marker/legend swatch.", max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(blank=True, help_text="Leave blank for a general/shared gate - set only for a gate specific to one club's fans.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gates', to='matches.club')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='matches.venue')),
            ],
            options={
                'verbose_name': 'Venue Gate',
                'verbose_name_plural': 'Venue Gates',
                'ordering': ['venue__name_ar', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MapPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('fan_home', 'Home Fan Association'), ('fan_away', 'Away Fan Association'), ('shared', 'Shared / General'), ('gate', 'Gate')], default='shared', max_length=10)),
                ('label', models.CharField(blank=True, help_text='Optional override text for this specific placement, e.g. "CAT 1 - North" for a second occurrence of CAT 1.', max_length=100)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='matches.venueseatingcategory')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_placements', to='matches.club')),
                ('position_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='matches.venueimage')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_placements', to='matches.venue')),
                ('gate', models.ForeignKey(blank=True, help_text='Set when this marker represents a gate rather than (or in addition to) a seating category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='matches.venuegate')),
            ],
            options={
                'verbose_name': 'Map Placement',
                'verbose_name_plural': 'Map Placements',
                'ordering': ['venue__name_ar', 'club__name_ar', 'sort_order', 'pk'],
            },
        ),
        migrations.RunPython(copy_positions_to_map_placements, noop_reverse),
        migrations.RemoveField(
            model_name='venueseatingcategory',
            name='position_image',
        ),
        migrations.RemoveField(
            model_name='venueseatingcategory',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='venueseatingcategory',
            name='position_y',
        ),
    ]
