# Generated by Django 6.0.7 on 2026-09-15 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0023_remove_venueseatingcategory_position_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=60)),
                ('name_en', models.CharField(max_length=60)),
                ('color', models.CharField(blank=True, help_text="Hex color (e.g. #f59e0b) for this tier's badge - shown alongside its name, never color-only.", max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Audience Tier',
                'verbose_name_plural': 'Audience Tiers',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.AddField(
            model_name='venueseatingcategory',
            name='audience_tier',
            field=models.ForeignKey(blank=True, help_text="This category's popularity/audience classification (e.g. Premium, Standard) - independent of its price, which is set per pricing-plan version instead.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='matches.audiencetier'),
        ),
    ]
