# Generated by Django 6.0.7 on 2026-08-25 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0010_club_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('events', 'Events'), ('seasons', 'Seasons'), ('experiences', 'Experiences'), ('dining', 'Dining')], max_length=20, unique=True)),
                ('name_ar', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Category Group',
                'verbose_name_plural': 'Category Groups',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventChecklistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Event Checklist Category',
                'verbose_name_plural': 'Event Checklist Categories',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='events.categorygroup')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['group__sort_order', 'sort_order', 'id'],
                'unique_together': {('group', 'name_en')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title_ar', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('gates_open_time', models.TimeField(blank=True, null=True)),
                ('sale_starts_at', models.DateTimeField(blank=True, null=True)),
                ('actual_release_at', models.DateTimeField(blank=True, help_text='When tickets actually went live, if different from the planned sale_starts_at.', null=True)),
                ('cms_status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('ready_for_cms', 'Ready for CMS'), ('sent_to_cms', 'Sent to CMS'), ('published', 'Published')], default='draft', max_length=30)),
                ('sent_to_cms_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.category')),
                ('sent_to_cms_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_sent_to_cms', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='matches.venue')),
            ],
            options={
                'ordering': ['event_date', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('checklist_updated', 'Checklist Updated'), ('status_changed', 'Status Changed'), ('sent_to_cms', 'Sent to CMS')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_activity_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Activity Log',
                'verbose_name_plural': 'Event Activity Log',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EventChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_items', to='events.eventchecklistcategory')),
            ],
            options={
                'verbose_name': 'Event Checklist Template Item',
                'verbose_name_plural': 'Event Checklist Template Items',
                'ordering': ('category__sort_order', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EventCategoryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('coordinator', 'Coordinator'), ('admin', 'Admin')], default='coordinator', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='events.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_category_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Category Access',
                'verbose_name_plural': 'Event Category Access',
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='EventChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('done', 'Done'), ('delayed', 'Delayed')], default='not_started', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('delay_reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_event_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='events.event')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_items', to='events.eventchecklisttemplateitem')),
            ],
            options={
                'verbose_name': 'Event Checklist Item',
                'verbose_name_plural': 'Event Checklist Items',
                'ordering': ('event_id', 'template_item__category__sort_order', 'template_item__sort_order', 'id'),
                'unique_together': {('event', 'template_item')},
            },
        ),
    ]
