# Generated by Django 6.0.7 on 2026-08-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('recommendation', 'Recommendations & Suggestions'), ('software', 'Software Improvements'), ('design', 'Design Improvements'), ('infrastructure', 'Infrastructure Improvements')], max_length=20)),
                ('submitted_by', models.CharField(help_text='Who suggested this.', max_length=150)),
                ('situation_before', models.TextField(help_text='The situation before this suggestion.')),
                ('suggestion', models.TextField(help_text='What was suggested.')),
                ('situation_after', models.TextField(blank=True, help_text='How things changed after implementation, if applicable.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], default='pending', max_length=20)),
                ('decision_reason', models.TextField(blank=True, help_text='Why it was accepted, rejected, or implemented.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feedback Entry',
                'verbose_name_plural': 'Feedback Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
