# Generated by Django 6.0.7 on 2026-08-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackentry',
            name='situation_before',
            field=models.TextField(blank=True, help_text='The situation before this suggestion. Filled in by the reviewer.'),
        ),
    ]
