# Generated by Django 6.0.7 on 2026-08-10 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_alter_feedbackentry_situation_before'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='e.g. 1.0.0', max_length=20, unique=True)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('highlights', models.TextField(help_text="What's new in this version - one item per line.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Release Note',
                'ordering': ['-release_date', '-id'],
            },
        ),
    ]
