# Generated by Django 6.0.7 on 2026-08-10 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_releasenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasenote',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
