# control_panel/design_tokens.py
"""
Design tokens auto-generated from Figma (Dark/Light).
Source files: ___Dark_tokens__3_.json / __Light_tokens__2_.json
Regenerate with scripts/generate_outputs.py whenever Figma tokens are re-exported.
"""

LIGHT_TOKENS = {
    'surface-surface-base': '#FCFCFC',
    'surface-surface-l1': '#FCFCFC',
    'surface-surface-l2': '#F5F5F6',
    'surface-surface-l3': '#CFD4E1',
    'surface-inverse-surface-base-inverse': '#18181B',
    'surface-inverse-surface-l1-inverse': '#18181B',
    'surface-inverse-surface-l2-inverse': '#2F2F32',
    'surface-inverse-surface-l3-inverse': '#5D5D5F',
    'backgrounds-bg-primary': '#FCFCFC',
    'backgrounds-bg-secondary': '#E6E8EE',
    'backgrounds-bg-tertiary': '#CFD4E1',
    'backgrounds-bg-disabled': '#0000001A',
    'backgrounds-bg-brand': '#FFD4E4',
    'backgrounds-bg-success': '#EAFFF1',
    'backgrounds-bg-success-20pct': '#17C65333',
    'backgrounds-bg-info': '#F8F5FF',
    'backgrounds-bg-info-20pct': '#7239EA33',
    'backgrounds-bg-warning': '#FFF8DD',
    'backgrounds-bg-warning-20pct': '#F6B10033',
    'backgrounds-bg-danger': '#FFEEF3',
    'backgrounds-bg-danger-20pct': '#F8285A33',
    'backgrounds-inverse-bg-primary-inverse': '#0B0B0E',
    'backgrounds-inverse-bg-secondary-inverse': '#5D5D5F',
    'backgrounds-inverse-bg-tertiary-inverse': '#8B8E9A',
    'backgrounds-brand-bg-brand': '#FF2C79',
    'backgrounds-brand-bg-brand-2': '#7B49FF',
    'backgrounds-brand-bg-brand-3': '#1D58FF',
    'backgrounds-brand-bg-brand-4': '#00FFD0',
    'backgrounds-brand-bg-brand-5': '#B3E100',
    'backgrounds-brand-bg-brand-6': '#FF7F29',
    'backgrounds-brand-bg-brand-7': '#FF4848',
    'backgrounds-brand-bg-brand-8': '#FFE000',
    'backgrounds-brand-bg-brand-9': '#FFA6EE',
    'backgrounds-overlayer-bg-overlay-50': '#00000080',
    'backgrounds-overlayer-bg-overlay-20': '#00000033',
    'backgrounds-overlayer-bg-overlay-10': '#0000001A',
    'backgrounds-overlayer-bg-overlay-5-invers': '#0000000D',
    'backgrounds-overlayer-bg-overlay-0-invers': '#00000003',
    'backgrounds-overlayer-bg-overlay-50-invers': '#FFFFFF80',
    'backgrounds-overlayer-bg-overlay-20-invers': '#FFFFFF33',
    'backgrounds-overlayer-bg-overlay-10-invers': '#FFFFFF1A',
    'backgrounds-overlayer-bg-overlay-5-inverse': '#FFFFFF0D',
    'backgrounds-overlayer-bg-overlay-0-inverse': '#FFFFFF03',
    'backgrounds-fixed-bg-light-fixed': '#FCFCFC',
    'backgrounds-fixed-bg-dark-fixed': '#0B0B0E',
    'content-content-primary': '#18181B',
    'content-content-secondary': '#8B8E9A',
    'content-content-tertiary': '#CFD4E1',
    'content-content-link': '#FF2C79',
    'content-content-success': '#17C653',
    'content-content-success-active': '#04B440',
    'content-content-brand-disabled': '#FFAAC9',
    'content-content-info': '#7239EA',
    'content-content-info-active': '#5A2AD7',
    'content-content-warning': '#F6B100',
    'content-content-warning-active': '#DFA000',
    'content-content-danger': '#F8285A',
    'content-content-danger-active': '#D81A48',
    'content-content-disabled': '#0000004D',
    'content-inverse-content-primary-inverse': '#F5F5F6',
    'content-inverse-content-secondary-inverse': '#E6E8EE',
    'content-inverse-content-tertiary-inverse': '#8B8E9A',
    'content-brand-content-brand': '#FF2C79',
    'content-brand-content-brand-2': '#7B49FF',
    'content-brand-content-brand-3': '#1D58FF',
    'content-brand-content-brand-4': '#00CCA6',
    'content-brand-content-brand-5': '#8FB400',
    'content-brand-content-brand-6': '#FF7F29',
    'content-brand-content-brand-7': '#FF4848',
    'content-brand-content-brand-8': '#CCB300',
    'content-fixed-content-light-fixed': '#F5F5F6',
    'content-fixed-content-dark-fixed': '#18181B',
    'borders-border-primary': '#18181B',
    'borders-border-secondary': '#5D5D5F',
    'borders-border-tertiary': '#CFD4E1',
    'borders-border-disabled': '#00000033',
    'borders-inverse-border-primary-inverse': '#F5F5F6',
    'borders-inverse-border-secondary-inverse': '#FFFFFF99',
    'borders-inverse-border-tertiary-inverse': '#FFFFFF33',
    'borders-fixed-border-light-fixed': '#FCFCFC',
    'borders-fixed-border-dark-fixed': '#18181B',
    'borders-brand-border-brand': '#FF2C79',
    'borders-brand-border-brand-2': '#7B49FF',
    'borders-brand-border-brand-3': '#1D58FF',
    'borders-brand-border-brand-4': '#00CCA6',
    'borders-brand-border-brand-5': '#8FB400',
    'borders-brand-border-brand-6': '#FF7F29',
    'borders-brand-border-brand-7': '#FF4848',
    'borders-brand-border-brand-8': '#CCB300',
}

DARK_TOKENS = {
    'surface-surface-base': '#0B0B0E',
    'surface-surface-l1': '#18181B',
    'surface-surface-l2': '#2F2F32',
    'surface-surface-l3': '#5D5D5F',
    'surface-inverse-surface-base-inverse': '#FCFCFC',
    'surface-inverse-surface-l1-inverse': '#F5F5F6',
    'surface-inverse-surface-l2-inverse': '#E6E8EE',
    'surface-inverse-surface-l3-inverse': '#CFD4E1',
    'backgrounds-bg-primary': '#0B0B0E',
    'backgrounds-bg-secondary': '#27272A',
    'backgrounds-bg-tertiary': '#5D5D5F',
    'backgrounds-bg-disabled': '#FFFFFF1A',
    'backgrounds-bg-brand': '#FFD4E4',
    'backgrounds-bg-success': '#17C65333',
    'backgrounds-bg-success-20pct': '#17C65333',
    'backgrounds-bg-info': '#7239EA33',
    'backgrounds-bg-info-20pct': '#7239EA33',
    'backgrounds-bg-warning': '#F6B10033',
    'backgrounds-bg-warning-20pct': '#F6B10033',
    'backgrounds-bg-danger': '#F8285A33',
    'backgrounds-bg-danger-20pct': '#F8285A33',
    'backgrounds-inverse-bg-primary-inverse': '#F5F5F6',
    'backgrounds-inverse-bg-secondary-inverse': '#8B8E9A',
    'backgrounds-inverse-bg-tertiary-inverse': '#5D5D5F',
    'backgrounds-brand-bg-brand': '#FF2C79',
    'backgrounds-brand-bg-brand-2': '#7B49FF',
    'backgrounds-brand-bg-brand-3': '#1D58FF',
    'backgrounds-brand-bg-brand-4': '#00FFD0',
    'backgrounds-brand-bg-brand-5': '#B3E100',
    'backgrounds-brand-bg-brand-6': '#FF7F29',
    'backgrounds-brand-bg-brand-7': '#FF4848',
    'backgrounds-brand-bg-brand-8': '#FFE000',
    'backgrounds-brand-bg-brand-9': '#FFA6EE',
    'backgrounds-overlayer-bg-overlay-50': '#FFFFFF80',
    'backgrounds-overlayer-bg-overlay-20': '#FFFFFF33',
    'backgrounds-overlayer-bg-overlay-10': '#FFFFFF1A',
    'backgrounds-overlayer-bg-overlay-5-invers': '#FFFFFF0D',
    'backgrounds-overlayer-bg-overlay-0-invers': '#FFFFFF03',
    'backgrounds-overlayer-bg-overlay-50-invers': '#00000080',
    'backgrounds-overlayer-bg-overlay-20-invers': '#00000033',
    'backgrounds-overlayer-bg-overlay-10-invers': '#0000001A',
    'backgrounds-overlayer-bg-overlay-5-inverse': '#0000000D',
    'backgrounds-overlayer-bg-overlay-0-inverse': '#00000003',
    'backgrounds-fixed-bg-light-fixed': '#0B0B0E',
    'backgrounds-fixed-bg-dark-fixed': '#FCFCFC',
    'content-content-primary': '#F5F5F6',
    'content-content-secondary': '#8B8E9A',
    'content-content-tertiary': '#5D5D5F',
    'content-content-link': '#FF5693',
    'content-content-success': '#17C653',
    'content-content-success-active': '#04B440',
    'content-content-brand-disabled': '#FFAAC9',
    'content-content-info': '#7239EA',
    'content-content-info-active': '#5A2AD7',
    'content-content-warning': '#F6B100',
    'content-content-warning-active': '#DFA000',
    'content-content-danger': '#F8285A',
    'content-content-danger-active': '#D81A48',
    'content-content-disabled': '#FFFFFF4D',
    'content-inverse-content-primary-inverse': '#0B0B0E',
    'content-inverse-content-secondary-inverse': '#27272A',
    'content-inverse-content-tertiary-inverse': '#5D5D5F',
    'content-brand-content-brand': '#FF2C79',
    'content-brand-content-brand-2': '#7B49FF',
    'content-brand-content-brand-3': '#1D58FF',
    'content-brand-content-brand-4': '#00FFD0',
    'content-brand-content-brand-5': '#B3E100',
    'content-brand-content-brand-6': '#FF7F29',
    'content-brand-content-brand-7': '#FF4848',
    'content-brand-content-brand-8': '#FFE000',
    'content-fixed-content-light-fixed': '#F5F5F6',
    'content-fixed-content-dark-fixed': '#18181B',
    'borders-border-primary': '#F5F5F6',
    'borders-border-secondary': '#8B8E9A',
    'borders-border-tertiary': '#2F2F32',
    'borders-border-disabled': '#FFFFFF33',
    'borders-inverse-border-primary-inverse': '#0B0B0E',
    'borders-inverse-border-secondary-inverse': '#00000099',
    'borders-inverse-border-tertiary-inverse': '#00000033',
    'borders-fixed-border-light-fixed': '#FCFCFC',
    'borders-fixed-border-dark-fixed': '#18181B',
    'borders-brand-border-brand': '#FF2C79',
    'borders-brand-border-brand-2': '#7B49FF',
    'borders-brand-border-brand-3': '#1D58FF',
    'borders-brand-border-brand-4': '#00FFD0',
    'borders-brand-border-brand-5': '#B3E100',
    'borders-brand-border-brand-6': '#FF7F29',
    'borders-brand-border-brand-7': '#FF4848',
    'borders-brand-border-brand-8': '#FFE000',
}

DESCRIPTIONS = {
    'surface-surface-base': 'Use this for surface backgrounds Like screen background, panels, modals, or sheets.',
    'surface-surface-l1': 'Use this for surface backgrounds Like screen background, panels, modals, or sheets.',
    'surface-surface-l2': 'Use this for surface backgrounds Like screen background, panels, modals, or sheets.',
    'surface-surface-l3': 'Use this for surface backgrounds Like screen background, panels, modals, or sheets.',
    'surface-inverse-surface-base-inverse': 'The opposite of the current mode. Use this for surface backgrounds Like screen background, panels, modals, or sheets.',
    'surface-inverse-surface-l1-inverse': 'The opposite of the current mode. Use this for surface backgrounds Like screen background, panels, modals, or sheets.',
    'surface-inverse-surface-l2-inverse': 'The opposite of the current mode. Use this for surface backgrounds Like screen background, panels, modals, or sheets.',
    'surface-inverse-surface-l3-inverse': 'The opposite of the current mode. Use this for surface backgrounds Like screen background, panels, modals, or sheets.',
    'backgrounds-bg-primary': 'Use for backgrounds of UI elements',
    'backgrounds-bg-secondary': 'Use for backgrounds of UI elements',
    'backgrounds-bg-tertiary': 'Use for backgrounds of UI elements',
    'backgrounds-bg-success': 'The opposite of the current mode. Use for backgrounds of UI elements that you want to strongly highlight',
    'backgrounds-bg-success-20pct': 'The opposite of the current mode. Use for backgrounds of UI elements that you want to strongly highlight',
    'backgrounds-inverse-bg-primary-inverse': 'The opposite of the current mode. Use for backgrounds of UI elements that you want to strongly highlight',
    'backgrounds-inverse-bg-secondary-inverse': 'The opposite of the current mode. Use for backgrounds of UI elements that you want to strongly highlight',
    'backgrounds-inverse-bg-tertiary-inverse': 'The opposite of the current mode. Use for backgrounds of UI elements that you want to strongly highlight',
}