# Generated by Django 6.0.7 on 2026-09-13 17:16

import django.db.models.deletion
import matches.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_club_is_test_club'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Pricing plan document uploaded by the home club (same allowed types/size as the SPL plan approval file).', upload_to='club_pricing_plans/', validators=[matches.models.validate_plan_approval_file])),
                ('version', models.PositiveIntegerField(help_text="1 for a match's first upload, incrementing per match - never reused or edited after creation.")),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded')], default='uploaded', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_plans', to='matches.club')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_pricing_plans', to='matches.match')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_pricing_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Club Pricing Plan',
                'verbose_name_plural': 'Club Pricing Plans',
                'ordering': ('-version',),
                'constraints': [models.UniqueConstraint(fields=('match', 'version'), name='unique_club_pricing_plan_version_per_match')],
            },
        ),
    ]
