# Generated by Django 6.0.7 on 2026-09-13 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_clubpricingplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpricingplan',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubpricingplan',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_pricing_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubpricingplan',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubpricingplan',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_pricing_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clubpricingplan',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('submitted_to_spl', 'Submitted to SPL'), ('submission_confirmed', 'Submission Confirmed')], default='uploaded', max_length=20),
        ),
    ]
