# Generated by Django 6.0.7 on 2026-09-14 13:19

import django.db.models.deletion
import matches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_venue_seat_type_venueimage_venueseatingcategory'),
        ('operations', '0003_clubpricingplan_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpricingplan',
            name='file',
            field=models.FileField(blank=True, help_text='Pricing plan document uploaded by the home club (same allowed types/size as the SPL plan approval file). Optional if category prices were entered instead.', null=True, upload_to='club_pricing_plans/', validators=[matches.models.validate_plan_approval_file]),
        ),
        migrations.CreateModel(
            name='ClubPricingPlanCategoryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_plan_prices', to='matches.venueseatingcategory')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_prices', to='operations.clubpricingplan')),
            ],
            options={
                'verbose_name': 'Club Pricing Plan Category Price',
                'verbose_name_plural': 'Club Pricing Plan Category Prices',
                'ordering': ('category__sort_order', 'category__code'),
                'constraints': [models.UniqueConstraint(fields=('plan', 'category'), name='unique_category_price_per_plan')],
            },
        ),
    ]
