# Generated by Django 6.0.7 on 2026-09-14 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_clubpricingplan_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpricingplan',
            name='spl_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='clubpricingplan',
            name='spl_decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubpricingplan',
            name='spl_decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_pricing_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubpricingplan',
            name='spl_decision_note',
            field=models.TextField(blank=True, help_text='Required when rejecting - explains what needs to change.'),
        ),
    ]
