# Generated by Django 6.0.7 on 2026-09-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_clubpricingplan_spl_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpricingplan',
            name='seat_map_snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='club_pricing_plan_snapshots/'),
        ),
    ]
