# Generated by Django 6.0.7 on 2026-09-15 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_clubpricingplan_seat_map_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpricingplan',
            name='home_percentage',
            field=models.PositiveIntegerField(blank=True, help_text="The club's own Home/Away ticket split for this plan, e.g. 70 means 70% Home / 30% Away.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
