# Generated by Django 6.0.7 on 2026-07-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchchecklistitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
