# Generated by Django 6.0.7 on 2026-07-29 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_matchchecklistitem_is_active'),
        ('matches', '0002_remove_match_unique_match_per_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistcategory',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Checklist Category', 'verbose_name_plural': 'Checklist Categories'},
        ),
        migrations.AlterModelOptions(
            name='checklisttemplateitem',
            options={'ordering': ('category__sort_order', 'sort_order', 'id'), 'verbose_name': 'Checklist Template Item', 'verbose_name_plural': 'Checklist Template Items'},
        ),
        migrations.AlterModelOptions(
            name='cmssubmission',
            options={'ordering': ('-created_at',), 'verbose_name': 'CMS Submission', 'verbose_name_plural': 'CMS Submissions'},
        ),
        migrations.AlterModelOptions(
            name='matchchecklistitem',
            options={'ordering': ('match_id', 'template_item__category__sort_order', 'template_item__sort_order', 'id'), 'verbose_name': 'Match Checklist Item', 'verbose_name_plural': 'Match Checklist Items'},
        ),
        migrations.RemoveConstraint(
            model_name='matchchecklistitem',
            name='unique_template_item_per_match',
        ),
        migrations.RemoveField(
            model_name='checklistcategory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='checklistcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='checklistcategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='checklisttemplateitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='checklisttemplateitem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='checklistcategory',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='checklistcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checklisttemplateitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_items', to='checklists.checklistcategory'),
        ),
        migrations.AlterField(
            model_name='checklisttemplateitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cmssubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchchecklistitem',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('done', 'Done'), ('delayed', 'Delayed')], default='not_started', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='matchchecklistitem',
            unique_together={('match', 'template_item')},
        ),
    ]
